ALTER TABLE animal
    ADD COLUMN origem VARCHAR(20) NOT NULL DEFAULT 'DESCONHECIDO';

ALTER TABLE animal
    ADD CONSTRAINT ck_animal_origem
    CHECK (origem IN ('COMPRA', 'NASCIMENTO', 'DESCONHECIDO'));
